# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DFF4FC
background         #191A1F
cursor             #788696

active_tab_foreground     #191A1F
active_tab_background     #DFF4FC
inactive_tab_foreground   #DFF4FC
inactive_tab_background   #191A1F

active_border_color   #DFF4FC
inactive_border_color #191A1F
bell_border_color     #0D1325

color0      #404046
color1		#0D1325
color2		#0D1325
color3		#1E4394
color4		#806698
color5		#3A75AF
color6		#7BA7B8
color7		#C9E7F2
color8		#8DA1A9
color9		#111931
color10		#111931
color11		#2859C5
color12		#AB88CA
color13		#4D9CE9
color14		#A4DFF6
color15		#C9E7F2
